-- Données d'exemple (fictives) : à exécuter après schema.sql.
-- Supprime-les quand tes premiers connecteurs alimentent la base :
--   delete from public.events where canonical_url like 'https://example.com/%';

insert into public.events (slug, title, summary, description, start_at, end_at, status, format, city, venue, primary_category, topics, technologies, audience, level, is_free, price_min, price_max, organizer_name, canonical_url) values
  ('paris-data-engineering-meetup-18', 'Paris Data Engineering Meetup #18', 'Deux retours d''expérience sur des pipelines lakehouse en production, suivis d''un temps de networking.', 'Au programme : migration d''un entrepôt historique vers une architecture médaillon, puis industrialisation de la qualité de données avec des tests automatisés. Les talks durent 25 minutes chacun, avec questions.', '2026-10-08T19:00:00+02:00', '2026-10-08T21:30:00+02:00', 'scheduled', 'in_person', 'Paris', 'Paris 13e', 'data', array['Data Engineering', 'Lakehouse', 'Qualité de données'], array['Databricks', 'dbt', 'Python'], array['Data engineers', 'Data analysts'], 'Intermédiaire', true, 0, 0, 'Paris Data Engineers', 'https://example.com/paris-data-engineering-meetup-18'),
  ('atelier-agents-llm-production', 'Atelier pratique : mettre des agents LLM en production', 'Une journée hands-on pour concevoir, évaluer et monitorer un agent LLM connecté à des outils métier.', 'Matinée consacrée à l''architecture d''un agent et à l''appel d''outils, après-midi dédié à l''évaluation et à l''observabilité. Ordinateur portable requis, environnement fourni.', '2026-10-14T09:30:00+02:00', '2026-10-14T17:30:00+02:00', 'scheduled', 'in_person', 'Paris', 'Paris 2e', 'ai', array['GenAI', 'Agents', 'LLMOps'], array['Python', 'LangGraph', 'OpenTelemetry'], array['Développeurs', 'Data scientists'], 'Avancé', false, 150, 150, 'Collectif IA Appliquée', 'https://example.com/atelier-agents-llm'),
  ('lyon-cloud-native-night-octobre', 'Lyon Cloud Native Night', 'Soirée communautaire autour de Kubernetes, du platform engineering et de l''observabilité.', 'Trois talks courts, une démo live d''un portail développeur interne, puis apéritif offert par l''hôte.', '2026-10-15T18:30:00+02:00', '2026-10-15T21:00:00+02:00', 'scheduled', 'in_person', 'Lyon', 'Lyon Part-Dieu', 'cloud', array['Kubernetes', 'Platform engineering'], array['Kubernetes', 'Backstage', 'Grafana'], array['DevOps', 'SRE', 'Développeurs'], 'Intermédiaire', true, 0, 0, 'Cloud Native Lyon', 'https://example.com/lyon-cloud-native-night'),
  ('afterwork-cyber-lille', 'Afterwork cybersécurité Lille', 'Retour d''expérience sur la gestion d''un incident ransomware, puis échanges entre professionnels de la sécurité.', null, '2026-10-21T18:30:00+02:00', '2026-10-21T21:00:00+02:00', 'scheduled', 'in_person', 'Lille', 'Euratechnologies', 'cyber', array['SOC', 'Réponse à incident'], '{}'::text[], array['RSSI', 'Analystes SOC'], 'Tous niveaux', true, 0, 0, 'Cyber Hauts-de-France', 'https://example.com/afterwork-cyber-lille'),
  ('hackathon-ia-mobilite-toulouse', 'Hackathon IA et mobilité', '48 heures pour prototyper des services de mobilité à partir de données ouvertes de transport.', 'Équipes de 3 à 5 personnes, jeux de données GTFS et trafic fournis, mentors présents tout le week-end. Pitch final devant un jury le dimanche après-midi.', '2026-10-24T09:00:00+02:00', '2026-10-25T18:00:00+01:00', 'scheduled', 'hybrid', 'Toulouse', 'Toulouse Montaudran', 'ai', array['Hackathon', 'Open data', 'Mobilité'], array['Python', 'GTFS'], array['Étudiants', 'Développeurs', 'Data scientists'], 'Tous niveaux', true, 0, 0, 'French Tech Toulouse', 'https://example.com/hackathon-ia-mobilite'),
  ('journee-recrutement-data-ia-paris', 'Journée recrutement Data et IA', 'Une trentaine d''entreprises recrutent des profils data, du stage au poste senior. Entretiens sur place.', 'Pense à apporter plusieurs CV. Des ateliers de relecture de CV ont lieu toutes les heures.', '2026-10-29T10:00:00+01:00', '2026-10-29T17:00:00+01:00', 'scheduled', 'in_person', 'Paris', 'Paris 15e', 'data', array['Recrutement', 'Carrière'], '{}'::text[], array['Étudiants', 'Juniors', 'Data engineers'], 'Débutant', true, 0, 0, 'Data Jobs France', 'https://example.com/journee-recrutement-data-ia'),
  ('conference-product-nantes', 'Conférence Product Nantes', 'Une journée de talks sur la discovery, la priorisation et le design de produits B2B.', null, '2026-11-05T09:00:00+01:00', '2026-11-05T18:00:00+01:00', 'scheduled', 'in_person', 'Nantes', 'Île de Nantes', 'product', array['Product management', 'UX', 'Discovery'], '{}'::text[], array['Product managers', 'Designers'], 'Intermédiaire', false, 49, 89, 'Product Ouest', 'https://example.com/conference-product-nantes'),
  ('startup-pitch-night-bordeaux', 'Startup Pitch Night Bordeaux', 'Huit startups en amorçage pitchent devant des business angels et des fonds régionaux.', null, '2026-11-12T18:00:00+01:00', '2026-11-12T21:30:00+01:00', 'scheduled', 'in_person', 'Bordeaux', 'Bordeaux Chartrons', 'startup', array['Pitch', 'Financement', 'Networking'], '{}'::text[], array['Fondateurs', 'Investisseurs'], 'Tous niveaux', true, 0, 0, 'Bordeaux Startups', 'https://example.com/startup-pitch-night-bordeaux'),
  ('webinaire-finops-kubernetes', 'Webinaire : réduire la facture Kubernetes avec le FinOps', '45 minutes pour mesurer et réduire le coût de clusters Kubernetes, avec démo et questions.', null, '2026-11-18T12:30:00+01:00', '2026-11-18T13:15:00+01:00', 'scheduled', 'online', null, null, 'devops', array['FinOps', 'Kubernetes'], array['Kubernetes', 'OpenCost'], array['DevOps', 'Architectes cloud'], 'Intermédiaire', true, 0, 0, 'FinOps France', 'https://example.com/webinaire-finops-kubernetes'),
  ('rennes-devops-day', 'Rennes DevOps Day', 'Conférence régionale sur la CI/CD, le SRE et l''observabilité, avec deux salles en parallèle.', null, '2026-11-26T09:00:00+01:00', '2026-11-26T18:00:00+01:00', 'scheduled', 'in_person', 'Rennes', 'Rennes Cesson-Sévigné', 'devops', array['CI/CD', 'SRE', 'Observabilité'], array['GitHub Actions', 'Prometheus', 'Terraform'], array['DevOps', 'SRE'], 'Intermédiaire', false, 30, 30, 'DevOps Bretagne', 'https://example.com/rennes-devops-day'),
  ('grenoble-deeptech-forum', 'Grenoble DeepTech Forum', 'Rencontres entre laboratoires, startups deeptech et industriels autour des semi-conducteurs et du quantique.', null, '2026-12-03T09:00:00+01:00', '2026-12-03T17:00:00+01:00', 'registration_closed', 'in_person', 'Grenoble', 'Presqu''île scientifique', 'deeptech', array['Semi-conducteurs', 'Quantique', 'Transfert technologique'], '{}'::text[], array['Fondateurs', 'Chercheurs', 'Industriels'], 'Tous niveaux', false, 120, 120, 'Alpes DeepTech', 'https://example.com/grenoble-deeptech-forum')
on conflict (slug) do nothing;

